# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-30 07:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.IntegerField()),
                ('website', models.URLField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('contact', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('category', models.CharField(choices=[('Student', 'Student'), ('Entreprener', 'Entreprener'), ('Expat', 'Expat/Diasporan'), ('Trust', 'Trust'), ('Institutional', 'Institutional'), ('Civil Servant', 'Civil Servant'), ('Other', 'Other')], max_length=100)),
                ('cell', models.IntegerField()),
                ('next_of_kin', models.CharField(max_length=100)),
                ('maritality', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], max_length=100)),
                ('banking_details', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
