# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-30 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_premium', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Company')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Personal')),
            ],
        ),
    ]
