# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-30 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premium',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='myapp.Company'),
        ),
        migrations.AlterField(
            model_name='premium',
            name='personal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal', to='myapp.Personal'),
        ),
    ]
