# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-30 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20181130_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premium',
            name='company',
        ),
        migrations.RemoveField(
            model_name='premium',
            name='personal',
        ),
        migrations.DeleteModel(
            name='Premium',
        ),
    ]
