# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-01 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_annually_biannulay_daily_monthly_weekly'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BiAnnulay',
            new_name='BiAnnually',
        ),
    ]
